server:
  port: 8084

spring:
  cloud:
    config:
      discovery:
        enabled: false
  config:
    import: optional:file:./config/,optional:classpath:/config/

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  jwt:
    secret: ${JWT_KEY}
    expiration-in-ms: 86400000
  originsUrl: http://localhost:5172

eureka:
  client:
    enabled: false